### PR TITLE
Added parseBool function in 'browser.js'. It was missing.

### PR DESCRIPTION
**Pull request by sticken88**
Just added the implementation of 'parseBool' in browser.js. There was an error in the console of the browser, clearly stating that the function was missing.
Everything should work fine now :)

### CODE REVIEW

**Comment by lemonzi** [comment]
Oops! I actually had that function globally defined somewhere else in the project where I use this library (and the code of which has been untouched for a while...). We did it like this:

``` javascript
    if (typeof value === "string") {
        value = value.replace(/^\s+|\s+$/g, "").toLowerCase();
        if (value === "true" || value === "false")
            return value === "true";
    }
    return; // returns undefined
```

I think at least checking if the input is a string is necessary, so it doesn't crash if it's actually not. The regex can be skipped. 

The coding style does not match either, by the way; I'm not using newlines before opening curly brackets.

However, I have to say that if we extend the project I'll probably switch to Socket.io 1.0, throw most of this code away and try to use an operational transform library.

Very happy to get the pull request though! Thanks a lot, contributions always welcome.

**Comment by sticken88** [comment]
You're right.

I added just that function because I don't need to take care of other cases (not a string etc.)

Sorry about different coding styles. This is my first fork/patch/pull request, so I really didn't think of that :). By the way thanks for accepting the pull request!

**Comment by sticken88** [comment]
Hey lemonzi! I modified the parseBool function according to your suggestions. Can you see the new function?

Cheers :)

**Comment by lemonzi** [comment]
Awesome! :)

**Comment by sticken88** [comment]
Perfect, thanks a lot :D!

**Pull request merged**
